# Generated by Django 5.0.7 on 2024-07-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='concerning_practices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='data_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='organization',
            field=models.CharField(max_length=255),
        ),
    ]
