# Generated by Django 4.2.16 on 2024-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modelinfo_concerning_practices_modelinfo_data_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='concerning_practices_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
    ]
